# Generated by Django 5.1.1 on 2024-10-18 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_task_deadline_alter_task_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='deadline',
        ),
        migrations.AddField(
            model_name='task',
            name='datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
